# Blinkenshell specific options (ssh'ed into a linux server)

# Generated by setup tool
export TZ='Europe/Brussels'
export LC_ALL='en_US.utf8'

# Use emacsclient
export EDITOR='emacsclient -t -a ""'
export ALTERNATE_EDITOR='emacs --daemon; emacsclient -t'
