;; Key bindings

(windmove-default-keybindings) ;; Shift+direction
(global-set-key (kbd "C-x f") 'recentf-ido-find-file)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-c n") 'cleanup-buffer)
(global-set-key (kbd "C-M-k") 'kill-word)
(global-set-key (kbd "C-M-h") 'backward-kill-word)
(global-set-key (kbd "C-M-g") 'backward-sexp) ;;TODO C-M-b doesn't work on OS X
(global-set-key (kbd "C-x C-i") 'ido-imenu)
(global-set-key (kbd "C-x j") 'join-line-or-lines-in-region)
(global-set-key (kbd "C-x O") (lambda () (interactive) (other-window -1)))
(global-set-key (kbd "C-M-=") 'comment-region)
(global-set-key (kbd "C-M-+") 'uncomment-region)
(global-set-key (kbd "TAB") 'smart-tab)
(global-set-key (kbd "C-c E") (lambda () (interactive)(eval-buffer)))
(global-set-key (kbd "C-x r v") 'list-registers)
(global-set-key (kbd "C-M-z") 'zap-back-to-char)
(global-set-key (kbd "C-c r") 'replace-string)
(global-set-key (kbd "C-x M-o") 'bury-buffer)
(global-set-key (kbd "C-c e") (lambda () (interactive)(find-file "~/.emacs")))
(global-set-key (kbd "C-c E") (lambda () (interactive)(eval-buffer)))
(global-set-key (kbd "C-c d") 'kill-line-backwards)
(global-set-key (kbd "C-c f") 'make-frame)
(global-set-key (kbd "C-M-y") 'kill-ring-search)
(global-set-key (kbd "C-c s") (lambda() (interactive)
                                (ispell-change-dictionary "nederlands")
                                (flyspell-buffer)))
(global-set-key (kbd "C-c x") 'swap-windows)
(global-set-key (kbd "M-g") 'goto-line)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "C-x C-m") 'smex)
(global-set-key (kbd "C-c M-x") 'execute-extended-command)
(global-set-key (kbd "C-c C-m") 'execute-extended-command)
(global-set-key (kbd "C-x g") 'magit-status)
(global-set-key (kbd "C-x M-c") (lambda() (interactive)
                                  (save-some-buffers t t)
                                  (kill-emacs)))
(global-set-key (kbd "RET") 'newline-and-indent)

(provide 'bindings)