;; Custom Themes
(defun color-theme-twilighter ()
  "Color theme by Marcus Crafter, based off the TextMate Twilight
theme, created 2008-04-18; modded bny Kieran Healy"
  (interactive)
  (color-theme-install
   '(color-theme-twilight
     ((background-color . "#1E1E1E")
      (background-mode . dark)
      (border-color . "#1E1E1E")
      (cursor-color . "#A7A7A7")
      (foreground-color . "#F8F8F8")
      (mouse-color . "sienna1"))
     (default ((t (:background "#1E1E1E" :foreground "#CACACA"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "#1E1E1E" :foreground "#CACACA"))))
     (font-lock-builtin-face ((t (:foreground "#CACACA"))))
     (font-lock-comment-face ((t (:italic t :foreground "#5F5A60"))))
     (font-lock-constant-face ((t (:foreground "#CF6A4C"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "#9B703F"))))
     (font-lock-keyword-face ((t (:foreground "#CDA869"))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))
     (font-lock-string-face ((t (:foreground "#8F9D6A"))))
     (font-lock-type-face ((t (:foreground "#9B703F"))))
     (font-lock-variable-name-face ((t (:foreground "#7587A6"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "#1E1E1E"))))
     (region ((t (:background "#27292A"))))
     (mode-line ((t (:background "grey75" :foreground "#1E1E1E"))))
     (highlight ((t (:background "#222222"))))
     (highline-face ((t (:background "SeaGreen"))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "#1E1E1E"))))
     (toolbar ((t (nil))))
     (underline ((nil (:underline nil))))
     (zmacs-region ((t (:background "snow" :foreground "ble")))))))

(defun color-theme-tm ()
  "Color theme by dngpng, created 2007-09-11."
  (interactive)
  (color-theme-install
   '(color-theme-tm
     ((background-color . "#111")
      (background-mode . dark)
      (border-color . "#111")
      (cursor-color . "yellow")
      (foreground-color . "#ddd")
      (mouse-color . "sienna1"))
     (default ((t (:background "#111" :foreground "#ddd"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t :slant italic))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "#111" :foreground "#ddd"))))
     (font-lock-builtin-face ((t (:foreground "#dd7b3b"))))
     (font-lock-comment-face ((t (:foreground "#666" ))))
     (font-lock-constant-face ((t (:foreground "#99cf50"))))
     (font-lock-doc-string-face ((t (:foreground "#9b859d"))))
     (font-lock-function-name-face ((t (:foreground "#e9c062" :bold t))))
     (font-lock-keyword-face ((t (:foreground "#cf6a4c" :bold t))))
     (font-lock-preprocessor-face ((t (:foreground "#aeaeae"))))
     (font-lock-reference-face ((t (:foreground "8b98ab"))))
     (font-lock-string-face ((t (:foreground "#65b042"))))
     (font-lock-type-face ((t (:foreground "#c5af75"))))
     (font-lock-variable-name-face ((t (:foreground "#3387cc"))))
     (font-lock-warning-face
      ((t (:bold t :background "#420e09" :foreground "#eeeeee"))))
     (erc-current-nick-face ((t (:foreground "#aeaeae"))))
     (erc-default-face ((t (:foreground "#ddd"))))
     (erc-keyword-face ((t (:foreground "#cf6a4c"))))
     (erc-notice-face ((t (:foreground "#666"))))
     (erc-timestamp-face ((t (:foreground "#65b042"))))
     (erc-underline-face ((t (:foreground "c5af75"))))
     (nxml-attribute-local-name-face ((t (:foreground "#3387cc"))))
     (nxml-attribute-colon-face ((t (:foreground "#e28964"))))
     (nxml-attribute-prefix-face ((t (:foreground "#cf6a4c"))))
     (nxml-attribute-value-face ((t (:foreground "#65b042"))))
     (nxml-attribute-value-delimiter-face ((t (:foreground "#99cf50"))))
     (nxml-namespace-attribute-prefix-face ((t (:foreground "#9b859d"))))
     (nxml-comment-content-face ((t (:foreground "#666"))))
     (nxml-comment-delimiter-face ((t (:foreground "#333"))))
     (nxml-element-local-name-face ((t (:foreground "#e9c062"))))
     (nxml-markup-declaration-delimiter-face ((t (:foreground "#aeaeae"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "#8b98ab"))))
     (nxml-prolog-keyword-face ((t (:foreground "#c5af75"))))
     (nxml-prolog-literal-content-face ((t (:foreground "#dad085"))))
     (nxml-tag-delimiter-face ((t (:foreground "#cda869"))))
     (nxml-tag-slash-face ((t (:foreground "#cda869"))))
     (nxml-text-face ((t (:foreground "#ddd"))))
     (gui-element ((t (:background "#0e2231" :foreground "black"))))
     (highlight ((t (:bold t :slant italic))))
     (highline-face ((t (:background "#4a410d"))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (mmm-default-submode-face ((t (:background "#111"))))
     (mode-line ((t (:background "#e6e5e4" :foreground "black"))))
     (primary-selection ((t (:background "#222"))))
     (region ((t (:background "#4a410d"))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (underline ((nil (:underline nil)))))))

(defun color-theme-blackboard ()
  "Color theme by JD Huntington, based off the TextMate
Blackboard theme, created 2008-11-27"
  (interactive)
  (color-theme-install
   '(color-theme-blackboard
     ((background-color . "#0C1021")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#A7A7A7")
      (foreground-color . "#F8F8F8")
      (mouse-color . "sienna1"))
     (default ((t (:background "#0C1021" :foreground "#F8F8F8"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "#0C1021" :foreground "#F8F8F8"))))
     (font-lock-builtin-face ((t (:foreground "#F8F8F8"))))
     (font-lock-comment-face ((t (:italic t :foreground "#AEAEAE"))))
     (font-lock-constant-face ((t (:foreground "#D8FA3C"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "#FF6400"))))
     (font-lock-keyword-face ((t (:foreground "#FBDE2D"))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))
     (font-lock-string-face ((t (:foreground "#61CE3C"))))
     (font-lock-type-face ((t (:foreground "#8DA6CE"))))
     (font-lock-variable-name-face ((t (:foreground "#FF6400"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (region ((t (:background "#253B76"))))
     (mode-line ((t (:background "grey75" :foreground "black"))))
     (highlight ((t (:background "#222222"))))
     (highline-face ((t (:background "SeaGreen"))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (toolbar ((t (nil))))
     (underline ((nil (:underline nil))))
     (zmacs-region ((t (:background "snow" :foreground "ble")))))))

(defun color-theme-gentooish ()
  "Mostly green and purple color theme by Brian Carper"
  (interactive)
  (color-theme-install
   '(color-theme-gentooish
     ((foreground-color . "#c0c0c0")
      (background-color . "#171717")
      (border-color . "black")
      (cursor-color . "green")
      (background-mode . dark))
     (bold ((t (:foreground "white" :weight normal))))
     (font-lock-builtin-face
      ((((class color) (min-colors 88) (background dark))
        (:foreground "#c476f1"))))
     (font-lock-comment-face
      ((((class color) (min-colors 88) (background dark))
        (:foreground "grey30" :slant italic))))
     (font-lock-function-name-face
      ((((class color) (min-colors 88) (background dark))
        (:foreground "#4cbbd1"))))
     (font-lock-keyword-face
      ((((class color) (min-colors 88) (background dark))
        (:foreground "#9a383a"))))
     (font-lock-string-face
      ((((class color) (min-colors 88) (background dark))
        (:background "#0f291a" :foreground "#5dff9e"))))
     (hi-blue ((((background dark)) (:background "grey20"))))
     (ido-first-match
      ((t (:background "#361d45" :foreground "#cf7dff" :weight bold))))
     (ido-only-match
      ((((class color)) (:background "#361d45" :foreground "#cf7dff"
                                     :weight bold))))
     (ido-subdir ((((min-colors 88) (class color)) (:foreground "#7dcfff"))))
     (linum ((t (:inherit shadow :background "grey12"))))
     (minibuffer-prompt ((((background dark)) (:foreground "#863335"))))
     (mode-line
      ((((class color) (min-colors 88))
        (:background "#333333" :foreground "#ffffff"
                     :box (:line-width -1 :color "#333333")))))
     (mode-line-highlight ((((class color) (min-colors 88)) nil)))
     (mode-line-inactive
      ((default (:inherit mode-line))
       (((class color) (min-colors 88) (background dark))
        (:foreground "#8b8b8b" :weight light))))
     (show-paren-match
      ((((class color) (background dark)) (:background "#005500"))))
     (tool-bar
      ((default (:foreground "black")) (((type x w32 ns) (class color))
                                        (:background "grey75")))))))

(defun color-theme-molokai ()
  "Color theme based on the Molokai color scheme for vim. By alloy-d"
  (interactive)
  (color-theme-install
   '(color-theme-molokai
     ((foreground-color . "#F8F8F2")
      (background-color . "#1B1D1E")
      (cursor-color . "#F8F8F0")
      (background-mode . dark))
     (default ((t (:foreground "#F8F8F2" :background "#1B1D1E"))))
     (bold ((t (:weight bold))))
     (bold-italic ((t (:weight bold :slant italic))))
     (custom-face-tag ((t (:foreground "#66D9EF" :weight bold))))
     (custom-state ((t (:foreground "#A6E22E"))))
     (italic ((t (:slant italic))))
     (region ((t (:background "#403D3D"))))
     (underline ((t (:underline t))))
     (css-selector ((t (:foreground "#F92672"))))
     (css-property ((t (:foreground "#66D9EF"))))
     (diff-added ((t (:foreground "#A6E22E" :weight bold))))
     (diff-context ((t (:foreground "#F8F8F2"))))
     (diff-file-header ((t (:foreground "#66D9EF" :background nil))))
     (diff-indicator-added ((t (:foreground "#A6E22E"))))
     (diff-indicator-removed ((t (:foreground "#F92672"))))
     (diff-header ((t (:foreground "#F8F8F2" :background "#232526"))))
     (diff-hunk-header ((t (:foreground "#AE81FF" :background "#232526"))))
     (diff-removed ((t (:foreground "#F92672" :weight bold))))
     (escape-glyph ((t (:foreground "#E6DB74"))))
     (minibuffer-prompt ((t (:foreground "#66D9EF"))))
     (mode-line
      ((t (:foreground "#F8F8F2" :background "#000000"
                       :box (:line-width 1 :color "#000000"
                                         :style released-button)))))
     (mode-line-buffer-id
      ((t (:foreground nil :background "#000000" :weight semi-bold))))
     (mode-line-inactive
      ((t (:foreground "#BCBCBC" :background "#000000"
                       :box (:line-width 1 :color "#232526")))))
     (mode-line-mousable ((t (:foreground "#BCBCBC" :background "#000000"))))
     (mode-line-mousable-minor-mode
      ((t (:foreground "#BCBCBC" :background "#000000"))))
     (font-lock-builtin-face ((t (:foreground "#A6E22E"))))
     (font-lock-comment-face ((t (:foreground "#465457" :slant italic))))
     (font-lock-comment-delimiter-face
      ((t (:foreground "#465457" :slant italic))))
     (font-lock-constant-face ((t (:foreground "#AE81FF"))))
     (font-lock-doc-face ((t (:foreground "#E6DB74" :slant italic))))
     (font-lock-function-name-face ((t (:foreground "#F92672" :slant italic))))
     (font-lock-keyword-face ((t (:foreground "#66D9EF"))))
     (font-lock-negation-char-face ((t (:weight bold))))
     (font-lock-preprocessor-face ((t (:foreground "#A6E22E"))))
     (font-lock-regexp-grouping-backslash ((t (:weight bold))))
     (font-lock-regexp-grouping-construct ((t (:weight bold))))
     (font-lock-string-face ((t (:foreground "#E6DB74"))))
     (font-lock-type-face ((t (:foreground "#66D9EF"))))
     (font-lock-variable-name-face ((t (:foreground "#F92672"))))
     (font-lock-warning-face ((t (:foreground "#FFFFFF"
                                              :background "#333333"))))
     (fringe ((t (:background "#232526"))))
     (highlight ((t (:foreground "#000000" :background "#C4BE89"))))
     (hl-line ((t (:background "#293739"))))
     (icompletep-choices ((t (:foreground "#F92672"))))
     (icompletep-determined ((t (:foreground "#A6E22E"))))
     (icompletep-keys ((t (:foreground "#F92672"))))
     (icompletep-nb-candidates ((t (:foreground "#AE81FF"))))
     (isearch ((t (:foreground "#C4BE89" :background "#000000"))))
     (isearch-fail ((t (:foreground "#FFFFFF" :background "#333333"))))
     (lazy-highlight ((t (:foreground "#465457" :background "#000000"))))
     (markdown-italic-face ((t (:slant italic))))
     (markdown-bold-face ((t (:weight bold))))
     (markdown-header-face ((t (:weight normal))))
     (markdown-header-face-1 ((t (:foreground "#66D9EF"))))
     (markdown-header-face-2 ((t (:foreground "#F92672"))))
     (markdown-header-face-3 ((t (:foreground "#A6E22E"))))
     (markdown-header-face-4 ((t (:foreground "#AE81FF"))))
     (markdown-header-face-5 ((t (:foreground "#E6DB74"))))
     (markdown-header-face-6 ((t (:foreground "#66D9EF"))))
     (markdown-inline-code-face ((t (:foreground "#66D9EF"))))
     (markdown-list-face ((t (:foreground "#A6E22E"))))
     (markdown-blockquote-face ((t (:slant italic))))
     (markdown-pre-face ((t (:foreground "#AE81FF"))))
     (markdown-link-face ((t (:foreground "#66D9EF"))))
     (markdown-reference-face ((t (:foreground "#66D9EF"))))
     (markdown-url-face ((t (:foreground "#E6DB74"))))
     (markdown-link-title-face ((t (:foreground "#F92672"))))
     (markdown-comment-face ((t (:foreground "#465457"))))
     (markdown-math-face ((t (:foreground "#AE81FF" :slant italic))))
     (mumamo-background-chunk-major ((t (:background "#272822"))))
     (mumamo-background-chunk-submode ((t (:background "#1B1D1E"))))
     (outline-1 ((t (:foreground "#66D9EF"))))
     (outline-2 ((t (:foreground "#F92672"))))
     (outline-3 ((t (:foreground "#A6E22E"))))
     (outline-4 ((t (:foreground "#AE81FF"))))
     (outline-5 ((t (:foreground "#E6DB74"))))
     (outline-6 ((t (:foreground "#66D9EF"))))
     (outline-7 ((t (:foreground "#F92672"))))
     (outline-8 ((t (:foreground "#A6E22E"))))
     (secondary-selection ((t (:background "#272822"))))
     (show-paren-match-face ((t (:foreground "#000000" :background "#FD971F"))))
     (show-paren-mismatch-face
      ((t (:foreground "#960050" :background "#1E0010"))))
     (widget-inactive-face ((t (:background "#ff0000"))))
     (woman-addition ((t (:foreground "#AE81FF"))))
     (woman-bold ((t (:foreground "#F92672"))))
     (woman-italic ((t (:foreground "#A6E22E"))))
     (woman-unknown ((t (:foreground "#66D9EF")))))))

(defun color-theme-wombat ()
  "Color theme 'wombat', taken from
http://dengmao.wordpress.com/2007/01/22/vim-color-scheme-wombat/#comment-1051,
created 2009-06-23."
  (interactive)
  (color-theme-install
   '(color-theme-wombat
     ((background-color . "#242424")
      (background-mode . dark)
      (border-color . "#888a85")
      (cursor-color . "#656565")
      (foreground-color . "#f6f3e8")
      (mouse-color . "#333333"))
     ((apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default
       ((t (:stipple nil :background "#242424" :foreground "#f6f3e8"
                     :inverse-video nil :box nil :strike-through nil
                     :overline nil :underline nil :slant normal :weight normal
                     :height 98 :width normal :foundry "outline"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "#888a85"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (comint-highlight-input ((t (:italic t :bold t :slant italic
                                          :weight bold))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (compilation-column-number ((t (:foreground "#cae682"))))
     (compilation-error ((t (:bold t :weight bold :foreground "#cc0000"))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:foreground "#cae682"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part
      ((t (:foundry "outline" :width normal :weight normal :slant normal
                    :underline nil :overline nil :strike-through nil :box nil
                    :inverse-video nil :foreground "#f6f3e8"
                    :background "#242424" :stipple nil :height 98))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "#656565"))))
     (dired-directory ((t (:foreground "#cae682"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "#cc0000"))))
     (dired-header ((t (:foreground "#cae682"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "#e5786d"))))
     (dired-marked ((t (:bold t :weight bold :foreground "#cc0000"))))
     (dired-perm-write
      ((t (:foundry "outline" :width normal :weight normal :slant normal
                    :underline nil :overline nil :strike-through nil :box nil
                    :inverse-video nil :foreground "#f6f3e8"
                    :background "#242424" :stipple nil :height 98))))
     (dired-symlink ((t (:foreground "#8ac6f2"))))
     (dired-warning ((t (:bold t :weight bold :foreground "#cc0000"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (font-lock-builtin-face ((t (:foreground "#8ac6f2"))))
     (font-lock-comment-delimiter-face
      ((t (:italic t :slant italic :foreground "#99968b"))))
     (font-lock-comment-face
      ((t (:italic t :foreground "#99968b" :slant italic))))
     (font-lock-constant-face ((t (:foreground "#e5786d"))))
     (font-lock-doc-face ((t (:italic t :foreground "#99968b" :slant italic))))
     (font-lock-function-name-face ((t (:foreground "#cae682"))))
     (font-lock-keyword-face ((t (:foreground "#8ac6f2"))))
     (font-lock-negation-char-face ((t (:foreground "#e7f6da"))))
     (font-lock-preprocessor-face ((t (:foreground "#e5786d"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face
      ((t (:italic t :foreground "#95e454" :slant italic))))
     (font-lock-type-face ((t (:foreground "#cae682"))))
     (font-lock-variable-name-face ((t (:foreground "#cae682"))))
     (font-lock-warning-face ((t (:bold t :foreground "#cc0000" :weight bold))))
     (fringe ((t (:background "grey10"))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkolivegreen"))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-fail ((t (:background "red4"))))
     (iswitchb-current-match ((t (:foreground "#cae682"))))
     (iswitchb-invalid-regexp
      ((t (:bold t :weight bold :foreground "#cc0000"))))
     (iswitchb-single-match
      ((t (:italic t :slant italic :foreground "#99968b"))))
     (iswitchb-virtual-matches ((t (:foreground "#8ac6f2"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "yellow" :foreground "black"))))
     (link ((t (:bold t :foreground "#8ac6f2" :underline t :weight bold))))
     (link-visited
      ((t (:bold t :weight bold :underline t :foreground "violet"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
     (minibuffer-noticeable-prompt ((t (nil))))
     (minibuffer-prompt ((t (:foreground "#729fcf"))))
     (mode-line ((t (:background "#333333" :foreground "#eeeeec"))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight
      ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#222222" :foreground "#cccddd"))))
     (mouse ((t (:background "#333333"))))
     (next-error ((t (:foreground "#f6f3e8" :background "#444444"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (org-date ((t (:foreground "LightSteelBlue" :underline t))))
     (org-hide ((t (:foreground "#2e3436"))))
     (org-level-1 ((t (:foreground "#cae682"))))
     (org-level-2 ((t (:foreground "#cae682"))))
     (org-level-3 ((t (:foreground "#8ac6f2"))))
     (org-level-4 ((t (:italic t :slant italic :foreground "#95e454"))))
     (org-level-5 ((t (:foreground "#e5786d"))))
     (org-todo ((t (:bold t :foreground "#8ac6f2" :weight bold))))
     (paren-face-match ((t (:foreground "#eeeeec" :background "#729fcf"))))
     (paren-face-match-light
      ((t (:foreground "#eeeeec" :background "#729fcf"))))
     (paren-face-mismatch ((t (:foreground "#2e3436" :background "#ad7fa8"))))
     (persp-selected-face ((t (:foreground "#729fcf"))))
     (query-replace ((t (:foreground "#2e3436" :background "#f57900"))))
     (region ((t (:background "#444444" :foreground "#f6f3e8"))))
     (scroll-bar ((t (:foreground "systemscrollbar"))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (sgml-namespace ((t (:foreground "#8ac6f2"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "#729fcf" :foreground "#eeeeec"))))
     (show-paren-mismatch ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (tmm-inactive ((t (:foreground "grey70"))))
     (tool-bar
      ((t (:background "systembuttonface" :foreground "systembuttontext"
                       :box (:line-width 1 :style released-button)))))
     (tooltip
      ((t (:background "systeminfowindow" :foreground "systeminfotext"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray")))))))

(defun color-theme-ir-black ()
  (interactive)
  (let ((*normal* "#F6F3E8")
        (*background* "#1e1e1e")
        (*cursor* "#FFFFFF")
        (*mouse* "sienna1")
        (*region* "#666666")
        (*current-line* "#151515")
        (*string* "#A8FF60")
        (*builtin* "#5EA6EA")
        (*keyword* "#0074E8")
        ;; TODO
        (*method* "#A8937A")
        (*comment* "#888a85")
        (*constant* "#99CC99")
        (*red* "#F1266F")
        (*operator* "#FFFFFF")
        (*type* "#E2BFAA")
        (*reference* "#99CC99")
        (*gui* "#eeeeee")
        (*gui2* "#555555")
        (*class* "#FFFFB6")
        (*variable* "#66D9EF")
        (*title* "#cae682"))

    (flet ((color (fgcolor &optional (bgcolor nil) (bold nil) (italic nil)
                           (underline nil))
                  `((t (,@(if fgcolor `(:foreground ,fgcolor))
                        ,@(if bgcolor `(:background ,bgcolor))
                        ,@(if bold '(:bold t))
                        ,@(if italic '(:italic t))
                        ,@(if underline '(:underline t))))))
           (face (face &rest args)
                 `(,(intern (concat "font-lock-" face "-face"))
                   ,(apply #'color args))))

      (color-theme-install
       `(color-theme-ir-black
         ((background-color . ,*background*)
          (background-mode . dark)
          (border-color . ,*background*)
          (cursor-color . ,*cursor*)
          (foreground-color . ,*normal*)
          (mouse-color . ,*mouse*))
         (default ,(color *normal* *background*))
         (blue ,(color "blue"))
         (border-glyph ((t (nil))))
         (buffers-tab ,(color *normal* *background*))
         ,(face "builtin" *builtin*)
         ,(face "comment" *comment*)
         ,(face "constant" *constant*)
         ,(face "doc-string" *string*)
         ,(face "function-name" *method*)
         ,(face "keyword" *keyword*)
         ,(face "preprocessor" *keyword*)
         ,(face "reference" *reference*)
         ,(face "regexp-grouping-backslash" *red*)
         ,(face "regexp-grouping-construct" *red*)
         ,(face "string" *string*)
         ,(face "type" *type*)
         ,(face "variable-name" *variable*)
         ,(face "warning" "white" *red*)
         (gui-element ,(color *background* *gui*))
         (region ,(color nil *region*))
         (minibuffer-prompt ,(color *builtin*))
         (mode-line ,(color *background* *gui*))
         (mode-line-inactive ,(color *background* *gui2*))
         (highlight ,(color nil *current-line*))
         (highline-face ,(color nil *current-line*))
         (italic ((t (nil))))
         (left-margin ((t (nil))))
         (text-cursor ,(color *background* *cursor*))
         (toolbar ((t (nil))))
         (bold ((t (:bold t))))
         (bold-italic ((t (:bold t))))
         (underline ((nil (:underline nil))))
         (link ,(color *keyword*))
         (ack-match ,(color *red* *background*))
         (ack-file ,(color *builtin*))
         (erc-notice-face ,(color *comment*))
         (erc-timestamp-face ,(color *red*))
         (erc-direct-msg-face ,(color *keyword*))
         (erc-nick-msg-face ,(color *keyword*))
         (erc-pal-face ,(color *keyword*))
         (erc-input-face ,(color *builtin*))
         (erc-current-nick-face ,(color *red*))
         (erc-my-nick-face ,(color *red*))
         (erc-prompt-face ,(color *red* *background*))
         (erc-header-line ((t (:underline nil))))
         ;; TODO
         (flyspell-duplicate ((t (:underline nil :foreground ,*type*))))
         (flyspell-incorrect ((t (:underline nil :foreground ,*red*))))
         (font-latex-italic-face
          ((t (:foreground ,*builtin* :italic t :underline nil))))
         (font-latex-bold-face
          ((t (:foreground ,*builtin* :bold t))))
         (font-latex-sectioning-1-face ,(color *title*))
         (font-latex-sectioning-2-face ,(color *title*))
         (font-latex-sectioning-3-face ,(color *title*))
         (font-latex-sectioning-4-face ,(color *title*))
         (font-latex-sectioning-5-face ,(color *title*))
         (comint-highlight-prompt ,(color *builtin*))
         (diredp-dir-heading ,(color *builtin* *background*))
         (diredp-inode+size ,(color *method*))
         (diredp-file-name ,(color *keyword*))
         (diredp-file-suffix ,(color *comment*))
         (diredp-dir-priv ,(color *builtin* *background*))
         (diredp-read-priv ,(color *comment* *background*))
         (diredp-write-priv ,(color *red* *background*))
         (diredp-exec-priv ,(color *string* *background*))
         (diredp-no-priv ,(color *comment* *background*))
         (diredp-date-time ,(color *string*))
         (diredp-flag-mark ,(color *type*))
         (diredp-flag-mark-line ,(color *region* *class*))
         (diredp-deletion ,(color *red* *background*))
         (diredp-deletion-file-name ,(color *red* *background*))
         (diredp-ignored-file-name ,(color *region*))
         (diredp-compressed-file-suffix ,(color *constant*))
         (diredp-executable-tag ,(color *constant*))
         (nxml-processing-instruction-delimiter-face ,(color *keyword*))
         (nxml-tag-delimiter-face ,(color *builtin*))
         (nxml-element-local-name-face ,(color *keyword*))
         (nxml-attribute-local-name-face ,(color *builtin*))
         (nxml-processing-instruction-target-face ,(color *keyword*))
         (nxml-attribute-value-face ,(color *string*))
         (nxml-prolog-literal-content-face ,(color *string*))
         (nxml-prolog-keyword-face ,(color *builtin*))
         (nxml-namespace-attribute-xmlns-face ,(color *builtin*))
         (ac-completion-face ((nil (:underline nil))))
         (ido-first-match ,(color *reference*))
         (ido-subdir ,(color *red* *background*)))))))

(defun color-theme-railscasts ()
  "MIT License Copyright (c) 2009 Oleg Shaldybin
 <oleg.shaldybin@gmail.com> Inspired by the brilliant Railscasts
 theme for TextMate."
  (interactive)
  (color-theme-install
   '(color-theme-railscasts
     ((background-color . "#232323")
      (background-mode . dark)
      (cursor-color . "#5A647E")
      (foreground-color . "#E6E1DC"))
     (default ((t (nil))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:italic t :bold t))))
     (fringe ((t (:background "#232323"))))
     (font-lock-builtin-face ((t (:foreground "#D0D0FF"))))
     (font-lock-comment-face ((t (:foreground "#BC9458" :italic t))))
     (font-lock-constant-face ((t (:foreground "#6D9CBE"))))
     (font-lock-doc-string-face ((t (:foreground "#A5C261"))))
     (font-lock-function-name-face ((t (:foreground "#FFC66D"))))
     (font-lock-keyword-face ((t (:foreground "#CC7833"))))
     (font-lock-preprocessor-face ((t (:foreground "#CC7833"))))
     (font-lock-reference-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-string-face ((t (:foreground "#A5C261"))))
     (font-lock-type-face ((t (:foreground "white"))))
     (font-lock-variable-name-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-warning-face ((t (:foreground "Pink"))))
     (paren-face-match-light
      ((t (:foreground "#FFC66D" :background "#555577"))))
     (highlight ((t (:background "darkolivegreen"))))
     (italic ((t (:italic t))))
     (modeline ((t (:background "#A5BAF1" :foreground "black"))))
     (modeline-buffer-id ((t (:background "#A5BAF1" :foreground "black"))))
     (modeline-mousable ((t (:background "#A5BAF1" :foreground "black"))))
     (modeline-mousable-minor-mode
      ((t (:background "#A5BAF1" :foreground "black"))))
     (region ((t (:background "#555577"))))
     (primary-selection ((t (:background "#555577"))))
     (isearch ((t (:background "#555555"))))
     (zmacs-region ((t (:background "#555577"))))
     (secondary-selection ((t (:background "darkslateblue"))))
     (flymake-errline ((t (:background "LightSalmon" :foreground "black"))))
     (flymake-warnline ((t (:background "LightSteelBlue" :foreground "black"))))
     (underline ((t (:underline t))))
     (minibuffer-prompt ((t (:bold t :foreground "#FF6600")))))))

(defun color-theme-blissterm ()
  "Terminal color theme by mrBliss."
  (interactive)
  (color-theme-install
   '(color-theme-blissterm
     ((background-color . "black")
      (background-mode . dark)
      (foreground-color . "white")
      (cursor-color . "white"))
     (default ((t (nil))))
     (mode-line-inactive ((t (:background "black" :foreground "white"))))
     (flyspell-duplicate ((t (:foreground "yellow"))))
     (flyspell-incorrect ((t (:foreground "red"))))
     (font-lock-builtin-face ((t (:foreground "magenta"))))
     (font-lock-comment-face ((t (:foreground "black" :bold t))))
     (font-lock-comment-delimiter-face ((t (:foreground "black" :bold t))))
     (font-lock-constant-face ((t (:foreground "blue"))))
     (font-lock-doc-string-face ((t (:foreground "green" :bold t))))
     (font-lock-string-face ((t (:foreground "green" :bold t))))
     (font-lock-function-name-face ((t (:foreground "green"))))
     (font-lock-keyword-face ((t (:foreground "cyan"))))
     (font-lock-type-face ((t (:underline t :foreground "yellow"))))
     (font-lock-variable-name-face ((t (:foreground "#7587A6" :bold t))))
     (font-lock-warning-face ((t (:bold t :foreground "#F9EE98"))))
     (erc-notice-face ((t (:foreground "black" :bold t))))
     (erc-timestamp-face ((t (:foreground "#F1266F"))))
     (erc-direct-msg-face ((t (:foreground "#0074e8"))))
     (erc-nick-msg-face ((t (:foreground "black" :bold t))))
     (erc-pal-face ((t (:foreground "green"))))
     (erc-input-face ((t (:foreground "yellow"))))
     (erc-current-nick-face ((t (:foreground "magenta"))))
     (erc-my-nick-face ((t (:foreground "magenta"))))
     (erc-prompt-face ((t (:foreground "magenta")))))))

(defun color-theme-tangotango ()
  "A color theme based on Tango Palette colors."
  ;; Color codes :
  ;; - blue :       "dodger blue"
  ;; - yellow :     "#edd400"
  ;; - green :      "#6ac214"
  ;; - orange/red : "tomato"
  (interactive)
  (color-theme-install
   '(color-theme-tangotango
     ((background-color . "#2e3434")
      (background-mode . dark)
      (border-color . "#888a85")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "#8ae234"))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (highlight ((t (:background "brown4" :foreground nil))))
     (border ((t (:background "#888a85"))))
     (fringe ((t (:background "grey10"))))
     (mode-line ((t (:foreground "#bbbbbc" :background "#222222" :box (:line-width 1 :color nil :style released-button)))))
     (mode-line-inactive ((t (:foreground "#bbbbbc" :background "#555753"))))
     (mode-line-buffer-id ((t (:bold t :foreground "orange" :background nil))))
     (region ((t (:background "dark slate blue"))))
     (link ((t (:underline t :foreground "dodger blue"))))
     (custom-link ((t (:inherit 'link))))
     (match ((t (:bold t :background "#e9b96e" :foreground "#2e3436"))))
     (tool-tips ((t (:inherit 'variable-pitch :foreground "black" :background "lightyellow"))))
     (tooltip ((t (:inherit 'variable-pitch :foreground "black" :background "lightyellow"))))
     (bold ((t (:bold t :underline nil :background nil))))
     (italic ((t (:italic t :underline nil :background nil))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-constant-face ((t (:foreground "#8ae234"))))
     (font-lock-doc-face ((t (:foreground "#888a85"))))
     (font-lock-keyword-face ((t (:foreground "#729fcf" :bold t))))
     (font-lock-string-face ((t (:foreground "#ad7fa8" :italic t))))
     (font-lock-type-face ((t (:foreground "#8ae234" :bold t))))
     (font-lock-variable-name-face ((t (:foreground "tomato"))))
     (font-lock-warning-face ((t (:bold t :foreground "#f57900"))))
     (font-lock-function-name-face ((t (:foreground "#edd400" :bold t))))
     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:foreground "#2e3436" :background "#e9b96e"))))
     (show-paren-match-face ((t (:foreground "#2e3436" :background "#73d216"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     (diary-face ((t (:bold t :foreground "IndianRed"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "DimGray"))))
     (eshell-ls-executable-face ((t (:bold t :foreground "Coral"))))
     (eshell-ls-missing-face ((t (:bold t :foreground "black"))))
     (eshell-ls-special-face ((t (:bold t :foreground "Gold"))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "White"))))
     (widget-button ((t (:bold t))))
     (widget-mouse-face ((t (:bold t :foreground "white" :background "brown4"))))
     (widget-field ((t (:foreground "orange" :background "gray30"))))
     (widget-single-line-field ((t (:foreground "orange" :background "gray30"))))
     (custom-group-tag ((t (:bold t :foreground "#edd400" :height 1.3))))
     (custom-variable-tag ((t (:bold t :foreground "#edd400" :height 1.1))))
     (custom-face-tag ((t (:bold t :foreground "#edd400" :height 1.1))))
     (custom-state-face ((t (:foreground "#729fcf"))))
     (custom-button  ((t (:box (:line-width 1 :style released-button) :background "grey50" :foreground "black"))))
     (custom-variable-button ((t (:inherit 'custom-button))))
     (custom-button-mouse  ((t (:inherit 'custom-button :background "grey60"))))
     (custom-button-unraised  ((t (:background "grey50" :foreground "black"))))
     (custom-button-mouse-unraised  ((t (:inherit 'custom-button-unraised :background "grey60"))))
     (custom-button-pressed  ((t (:inherit 'custom-button :box (:style pressed-button)))))
     (custom-button-mouse-pressed-unraised  ((t (:inherit 'custom-button-unraised :background "grey60"))))
     (custom-documentation ((t (:italic t))))
     (message-cited-text ((t (:foreground "#edd400"))))
     (gnus-cite-face-1 ((t (:foreground "#ad7fa8"))))
     (gnus-cite-face-2 ((t (:foreground "sienna4"))))
     (gnus-cite-face-3 ((t (:foreground "khaki4"))))
     (gnus-cite-face-4 ((t (:foreground "PaleTurquoise4"))))
     (gnus-group-mail-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "light cyan"))))
     (gnus-group-mail-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "turquoise"))))
     (gnus-group-mail-3-empty-face ((t (:foreground "#729fcf"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "#edd400"))))
     (gnus-group-mail-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "dodger blue"))))
     (gnus-group-news-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "light cyan"))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise"))))
     (gnus-group-news-3-empty-face ((t (:foreground "#729fcf"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "#edd400"))))
     (gnus-group-news-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "dodger blue"))))
     (gnus-header-name-face ((t (:bold t :foreground "#729fcf"))))
     (gnus-header-from ((t (:bold t :foreground "#edd400"))))
     (gnus-header-subject ((t (:foreground "#edd400"))))
     (gnus-header-content ((t (:italic t :foreground "#8ae234"))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3"))))
     (gnus-signature-face ((t (:italic t :foreground "dark grey"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "rotal blue"))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "lime green"))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "tomato"))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "white"))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "lime green"))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "royal blue"))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "dark red"))))
     (gnus-summary-low-unread-face ((t (:italic t :foreground "white"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "royal blue"))))
     (gnus-summary-normal-read-face ((t (:foreground "lime green"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "indian red"))))
     (gnus-summary-normal-unread-face ((t (:foreground "white"))))
     (gnus-summary-selected ((t (:background "brown4" :foreground "white"))))
     (message-header-name-face ((t (:foreground "tomato"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3"))))
     (message-header-other-face ((t (:foreground "LightSkyBlue3"))))
     (message-header-xheader-face ((t (:foreground "DodgerBlue3"))))
     (message-header-subject ((t (:foreground "white"))))
     (message-header-to ((t (:foreground "white"))))
     (message-header-cc ((t (:foreground "white"))))
     (org-hide ((t (:foreground "#2e3436"))))
     (org-level-1 ((t (:bold t :foreground "dodger blue" :height 1.5))))
     (org-level-2 ((t (:bold nil :foreground "#edd400" :height 1.2))))
     (org-level-3 ((t (:bold t :foreground "#6ac214" :height 1.0))))
     (org-level-4 ((t (:bold nil :foreground "tomato" :height 1.0))))
     (org-date ((t (:underline t :foreground "magenta3"))))
     (org-footnote  ((t (:underline t :foreground "magenta3"))))
     (org-link ((t (:foreground "skyblue2" :background "#2e3436"))))
     (org-special-keyword ((t (:foreground "brown"))))
     (org-verbatim ((t (:foreground "#eeeeec" :underline t :slant italic))))
     (org-block ((t (:foreground "#bbbbbc"))))
     (org-quote ((t (:inherit org-block :slant italic))))
     (org-verse ((t (:inherit org-block :slant italic))))
     (org-todo ((t (:bold t :foreground "Red"))))
     (org-done ((t (:bold t :foreground "ForestGreen"))))
     (org-agenda-structure ((t (:weight bold :foreground "tomato"))))
     (org-agenda-date ((t (:foreground "#6ac214"))))
     (org-agenda-date-weekend ((t (:weight normal :foreground "dodger blue"))))
     (org-agenda-date-today ((t (:weight bold :foreground "#edd400"))))
     (anything-header ((t (:bold t :background "grey15" :foreground "#edd400"))))
     (ess-jb-comment-face ((t (:background "#2e3436" :foreground "firebrick" :slant italic))))
     (ess-jb-hide-face ((t (:background "#2e3436" :foreground "#243436"))))
     (ess-jb-h1-face ((t (:height 1.6 :foreground "dodger blue" :slant normal))))
     (ess-jb-h2-face ((t (:height 1.4 :foreground "#6ac214" :slant normal))))
     (ess-jb-h3-face ((t (:height 1.2 :foreground "#edd400" :slant normal))))
     (ecb-default-highlight-face ((t (:background "#729fcf"))))
     (ecb-tag-header-face ((t (:background "#f57900"))))
     (magit-header ((t (:foreground "#edd400"))))
     (magit-diff-add ((t (:foreground "#729fcf"))))
     (magit-item-highlight ((t (:weight extra-bold :inverse-video t)))))))

(defun color-theme-bespin ()
  "Based on Mozilla's Bespin. By mrBliss."
  (interactive)
  (color-theme-install
   '(color-theme-bespin
     ((background-color . "#302620")
      (foreground-color . "#BAAE9E")
      (cursor-color . "#ffffff"))
     (default ((t (nil))))
     (lazy-highlight
      ((t (:background "#5EA6EA" :foreground "#ffffff"
                       :box nil))))
     (highlight
      ((t (:background "#0074e8" :foreground "#ffffff"))))
     (modeline
      ((t (:background "#28201A" :foreground "#BAAE9E"
                       :box (:line-width 1 :color "#4c4a41" :style nil)))))
     (modeline-buffer-id ((t nil)))
     (mode-line-highlight
      ((t (:box (:line-width 1 :color "grey40" :style released-button)))))
     (mode-line-inactive
      ((t (:background "#1e1915" :foreground "#BAAE9E"
                       :box (:line-width 1 :color "#1e1915")))))
     (minibuffer-prompt ((t (:foreground "#5EA6EA"))))
     (flyspell-duplicate
      ((t (:foreground "#FF8844" :bold t :underline t))))
     (flyspell-incorrect
      ((t (:foreground "#F1266F" :bold t :underline t))))
     (font-lock-builtin-face ((t (:foreground "#5EA6EA"))))
     (font-lock-comment-face
      ((t (:italic t :foreground "#666666" :background "#382C25"))))
     (font-lock-constant-face ((t (:foreground "#DDF2A4"))))
     (font-lock-doc-string-face ((t (:foreground "#5EA6EA"))))
     (font-lock-string-face ((t (:foreground "#00920A"))))
     (font-lock-function-name-face ((t (:foreground "#A8937A" :italic t))))
     (font-lock-keyword-face ((t (:foreground "#0074e8"))))
     (font-lock-type-face ((t (:foreground "#89BDFF"))))
     (font-lock-variable-name-face ((t (:foreground "#7587A6" :bold t))))
     (font-lock-warning-face ((t (:bold t :foreground "#F9EE98"))))
     (comint-highlight-prompt ((t (:foreground "#5EA6EA"))))
     (highlight-80+ ((t (:background "#F9EE98"))))
     (hl-line ((t (:background "#211B15"))))
     (region ((t (:background "#f8fab7"))))
     (link ((t (:foreground "#5EA6EA" :underline t))))
     (ido-subdir ((t (:foreground "#F1266F"))))
     (diff-added ((t (:foreground "green3"))))
     (diff-indicator-added ((t (:foreground "green3"))))
     (diff-changed ((t (:foreground "#FF8844"))))
     (diff-indicator-changed ((t (:foreground "#FF8844"))))
     (diff-removed ((t (:foreground "red3"))))
     (diff-indicator-removed ((t (:foreground "red3"))))
     (diredp-dir-heading
      ((t (:background nil :underline t :foreground "#5EA6EA"))))
     (diredp-inode+size ((t (:foreground "#A8937A" :italic t))))
     (diredp-file-name ((t (:foreground "#0074e8"))))
     (diredp-file-suffix ((t (:foreground "#7587A6"))))
     (diredp-dir-priv
      ((t (:background nil :italic t :foreground "#89BDFF"))))
     (diredp-read-priv ((t (:background nil :foreground "#BAAE9E"))))
     (diredp-write-priv ((t (:background nil :foreground "#F1266F"))))
     (diredp-exec-priv ((t (:background nil :foreground "#FF8844"))))
     (diredp-no-priv ((t (:background nil :foreground "#BAAE9E"))))
     (diredp-date-time ((t (:foreground "#00920A"))))
     (diredp-flag-mark ((t (:background nil :foreground "#FF8844"))))
     (diredp-flag-mark-line ((t (:background "#F9EE98" :foreground "#666666"))))
     (diredp-deletion ((t (:background nil :foreground "#F1266F"))))
     (diredp-deletion-file-name ((t (:background nil :foreground "#F1266F"))))
     (diredp-ignored-file-name ((t (:foreground "#666666"))))
     (diredp-compressed-file-suffix ((t (:foreground "#DDF2A4"))))
     (diredp-executable-tag ((t (:foreground "#DDF2A4"))))
     (erc-notice-face ((t (:foreground "#666666"))))
     (erc-timestamp-face ((t (:foreground "#F1266F"))))
     (erc-direct-msg-face ((t (:foreground "#0074e8"))))
     (erc-nick-msg-face ((t (:foreground "#0074e8" :bold t))))
     (erc-pal-face ((t (:foreground "#0074e8"))))
     (erc-input-face ((t (:foreground "#5EA6EA" :italic t))))
     (erc-current-nick-face ((t (:foreground "#F1266F"))))
     (erc-my-nick-face ((t (:foreground "#A8937A" :italic t))))
     (erc-prompt-face ((t (:background nil :foreground "#F1266F"))))
     (font-latex-warning-face ((t (:foreground "#F9EE98"))))
     (font-latex-italic-face
      ((t (:foreground "#BAAE9E" :italic t :underline nil))))
     (font-latex-bold-face ((t (:foreground "#BAAE9E" :bold t))))
     (font-latex-sectioning-1-face ((t (:foreground "#BAAE9E"))))
     (font-latex-sectioning-2-face ((t (:foreground "#BAAE9E"))))
     (font-latex-sectioning-3-face ((t (:foreground "#BAAE9E"))))
     (font-latex-sectioning-4-face ((t (:foreground "#BAAE9E"))))
     (font-latex-sectioning-5-face ((t (:foreground "#BAAE9E"))))
     (nxml-processing-instruction-delimiter-face ((t (:foreground "#0074e8"))))
     (nxml-tag-delimiter-face ((t (:foreground "#5EA6EA"))))
     (nxml-element-local-name-face ((t (:foreground "#0074e8"))))
     (nxml-attribute-local-name-face ((t (:foreground "#5EA6EA"))))
     (nxml-processing-instruction-target-face ((t (:foreground "#0074e8"))))
     (nxml-attribute-value-face ((t (:foreground "#00920A"))))
     (nxml-prolog-literal-content-face ((t (:foreground "#00920A"))))
     (nxml-prolog-keyword-face ((t (:foreground "#5EA6EA"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "#5EA6EA"))))
     (escape-glyph ((t (:foreground "#F1266F"))))
     (markdown-inline-code-face ((t (:foreground "#5EA6EA"))))
     (markdown-pre-face ((t (:foreground "#5EA6EA"))))
     (undo-tree-visualizer-current-face ((t (:foreground "#F1266F"))))
     (slime-repl-result-face ((t (:foreground "#a8937a")))))))


(defun color-theme-dark-violet ()
  "A dark, violet and blue color-theme by mrBliss."
  (interactive)
  (color-theme-install
   '(color-theme-dark-violet
     ((background-color . "#1C1C1C")
      (foreground-color . "#DDEEDD")
      (cursor-color . "#ffffff"))
     (default ((t (nil))))

     (modeline
      ((t (:background "#4E4E4E" :foreground "#FFFFFF"
                       :box (:line-width 1 :color "#3D3D3D" :style nil)))))
     (mode-line-inactive
      ((t (:background "#353535" :foreground "#DDEEDD"
                       :box (:line-width 1 :color "#454545")))))

     (font-lock-builtin-face ((t (:foreground "#D7AFD7"))))
     (font-lock-comment-face ((t (:foreground "#808080" :background "#1A1A1A"))))
     (font-lock-constant-face ((t (:foreground "#86A2BE"))))
     (font-lock-string-face ((t (:foreground "#5E468C" :background "#202020"))))
     (font-lock-function-name-face ((t (:foreground "#9C75DD" :italic t))))
     (font-lock-keyword-face ((t (:foreground "#8CC8DB"))))
     (font-lock-type-face ((t (:foreground "#6096BF"))))
     (font-lock-variable-name-face ((t (:foreground "#395573" :bold t))))
     (font-lock-warning-face ((t (:bold t :foreground "#AFD787"))))
     ;; (font-lock-doc-string-face ((t (:foreground "#5EA6EA"))))

     (region ((t (:background "#477AB3" :foreground "#FFFFFF"))))
     (highlight ((t (:background "#477AB3" :foreground "#ffffff"))))
     (highlight-80+ ((t (:background "#BF4D80"))))
     (hl-line ((t (:background "#222222"))))

     (minibuffer-prompt ((t (:foreground "#6096BF"))))
     (link ((t (:foreground "#6096BF" :underline t))))
     (comint-highlight-prompt ((t (:foreground "#6096BF"))))
     (geiser-font-lock-doc-link ((t (:foreground "#6096BF" :underline t))))

     (info-menu-star ((t (:foreground "#BF4D80"))))
     (escape-glyph ((t (:foreground "#BF4D80"))))
     (ido-subdir ((t (:foreground "#AF87D7"))))
     (ido-first-match ((t (:foreground "#5E468C"))))
     (ido-only-match ((t (:foreground "#31658C"))))
     (undo-tree-visualizer-current-face ((t (:foreground "#BF4D80"))))

     (flyspell-duplicate
      ((t (:foreground "#FF907A" :bold t :underline t))))
     (flyspell-incorrect
      ((t (:foreground "#BF4D80" :bold t :underline t))))

     (flymake-errline ((t (:underline "red" :background nil))))
     (flymake-warnline ((t (:underline "#FF907A" :background nil))))

     (ensime-errline-highlight ((t (:underline "red" :background nil))))

     (diff-added ((t (:foreground "green3"))))
     (diff-indicator-added ((t (:foreground "green3"))))
     (diff-changed ((t (:foreground "#FF907A"))))
     (diff-indicator-changed ((t (:foreground "#FF907A"))))
     (diff-removed ((t (:foreground "red3"))))
     (diff-indicator-removed ((t (:foreground "red3"))))

     (diredp-dir-heading
      ((t (:background nil :underline t :foreground "#6096BF"))))
     (diredp-inode+size ((t (:foreground "#8CC8DB" :italic t))))
     (diredp-file-name ((t (:foreground "#A9D1DF"))))
     (diredp-file-suffix ((t (:foreground "#8B769F"))))
     (diredp-dir-priv
      ((t (:background nil :italic t :foreground "#6096BF"))))
     (diredp-link-priv ((t (:foreground "#287373"))))
     (diredp-rare-priv ((t (:foreground "#BF4D80" :background nil))))
     (diredp-other-priv ((t (:foreground "#477AB3" :background nil))))
     (diredp-read-priv ((t (:background nil :foreground "#6096BF"))))
     (diredp-write-priv ((t (:background nil :foreground "#D7AFD7"))))
     (diredp-exec-priv ((t (:background nil :foreground "#5E468C"))))
     (diredp-no-priv ((t (:background nil :foreground "#DDEEDD"))))
     (diredp-date-time ((t (:foreground "#8CC8DB"))))
     (diredp-flag-mark ((t (:background nil :foreground "#8CC8DB"))))
     (diredp-flag-mark-line ((t (:background "#8CC8DB" :foreground "#1A1A1A"))))
     (diredp-deletion ((t (:background nil :foreground "#FF00FF"))))
     (diredp-deletion-file-name ((t (:background nil :foreground "#BF4D80"))))
     (diredp-ignored-file-name ((t (:foreground "#808080"))))
     (diredp-compressed-file-suffix ((t (:foreground "#D7AF87"))))
     (diredp-executable-tag ((t (:foreground "#BF4D80"))))
     (diredp-symlink ((t (:foreground "#287373"))))

     (magit-section-title ((t (:foreground "#86A2BE"))))
     (magit-branch ((t (:foreground "#D7AFD7"))))
     (magit-item-highlight ((t (:background "#353535"))))
     (magit-log-sha1 ((t (:foreground "#AF87D7"))))

     (erc-default-face ((t (:foreground "#999999"))))
     (erc-notice-face ((t (:foreground "#3D3D3D"))))
     (erc-timestamp-face ((t (:foreground "#BF4D80"))))
     (erc-direct-msg-face ((t (:foreground "#BF4D80"))))
     (erc-nick-msg-face ((t (:foreground "#BF4D80" :bold t))))
     (erc-pal-face ((t (:foreground "#53A6A6"))))
     (erc-input-face ((t (:foreground "#86A2BE" :italic t))))
     (erc-current-nick-face ((t (:foreground "#BF4D80"))))
     (erc-nick-default-face ((t (:foreground "#477AB3"))))
     (erc-my-nick-face ((t (:foreground "#BF4D80" :italic t))))
     (erc-prompt-face ((t (:background nil :foreground "#6096BF"))))

     (font-latex-warning-face ((t (:foreground "#FF00FF"))))
     (font-latex-italic-face
      ((t (:foreground "#AF87D7" :italic t :underline nil))))
     (font-latex-bold-face ((t (:foreground "#849DA2" :bold t))))
     (font-latex-sectioning-1-face ((t (:foreground "#395573"))))
     (font-latex-sectioning-2-face ((t (:foreground "#31658C"))))
     (font-latex-sectioning-3-face ((t (:foreground "#6096BF"))))
     (font-latex-sectioning-4-face ((t (:foreground "#86A2BE"))))
     (font-latex-sectioning-5-face ((t (:foreground "#A9D1DF"))))
     (font-latex-sedate-face ((t (:foreground "#6096BF"))))

     (markdown-inline-code-face ((t (:foreground "#6096BF"))))
     (markdown-pre-face ((t (:foreground "#6096BF"))))

     (nxml-processing-instruction-delimiter-face ((t (:foreground "#31658C"))))
     (nxml-tag-delimiter-face ((t (:foreground "#31658C"))))
     (nxml-element-local-name-face ((t (:foreground "#31658C"))))
     (nxml-attribute-local-name-face ((t (:foreground "#86A2BE"))))
     (nxml-processing-instruction-target-face ((t (:foreground "#31658C"))))
     (nxml-attribute-value-face ((t (:foreground "#9C75DD"))))
     (nxml-attribute-value-delimiter-face ((t (:foreground "#9C75DD"))))
     (nxml-comment-content-face ((t (:foreground "#808080"))))
     (nxml-comment-delimiter-face ((t (:foreground "#808080"))))
     (nxml-entity-ref-name-face ((t (:foreground "#D7AF87"))))
     (nxml-entity-ref-delimiter-face ((t (:foreground "#D7AF87"))))
     ;; (nxml-prolog-literal-content-face ((t (:foreground "#808080"))))
     ;; (nxml-prolog-keyword-face ((t (:foreground "#5EA6EA"))))
     ;; (nxml-namespace-attribute-xmlns-face ((t (:foreground "#5EA6EA"))))

     (w3m-anchor ((t (:foreground "#6096BF" ))))
     (w3m-header-line-location-title ((t (:foreground "#9C75DD"))))
     (w3m-header-line-location-content ((t (:foreground "#D7AF87"))))
     (w3m-image-anchor ((t (:background "#31658C" :foreground "#DDEEDD"))))

     (clojure-parens ((t (:foreground "#4E4E4E"))))
     (clojure-keyword ((t (:foreground "#45b8f2"))))
     (clojure-double-quote ((t (:foreground "#5E468C"))))
     (clojure-special ((t (:foreground "#AF87D7")))))))

(defun color-theme-solarized-light ()
  "Color theme by Ethan Schoonover, ported to Emacs by Greg
Pfeil, edited by mrBliss."
  (interactive)
  (let ((base03  "#002b36")
        (base02  "#073642")
        (base01  "#586e75")
        (base00  "#657b83")
        (base0   "#839496")
        (base1   "#93a1a1")
        (base2   "#eee8d5")
        (base25  "#f9f2e0")
        (base3   "#fdf6e3")
        (yellow  "#b58900")
        (orange  "#cb4b16")
        (red     "#dc322f")
        (magenta "#d33682")
        (violet  "#6c71c4")
        (blue    "#268bd2")
        (cyan    "#2aa198")
        (green   "#859900"))
    (color-theme-install
     `(color-theme-solarized-light
       ((foreground-color . ,base00)
        (background-color . ,base3)
        (background-mode . light)
        (cursor-color . ,base0))
       (default ((t (:foreground ,base00 :background ,base3))))
       (cursor
        ((t (:foreground ,base0 :background ,base03 :inverse-video t))))
       (header-line ((t (:foreground ,base00 :background ,base02))))
       (fringe ((t (:foreground ,base1 :background ,base2))))

       (mode-line ((t (:foreground ,base01 :background ,base2
                                   :box (:color ,base2 :style nil)))))
       (mode-line-buffer-id ((t (:foreground ,base01))))
       (mode-line-inactive
        ((t (:foreground ,base00  :background ,base3
                         :box (:color ,base3 :style nil)))))

       (font-lock-builtin-face ((t (:foreground ,magenta))))
       (font-lock-comment-face ((t (:foreground ,base1 :italic t
                                                :background ,base25))))
       (font-lock-constant-face ((t (:foreground ,cyan))))
       (font-lock-string-face ((t (:foreground ,cyan :background nil))))
       (font-lock-function-name-face ((t (:foreground ,blue))))
       (font-lock-keyword-face ((t (:foreground ,green))))
       (font-lock-type-face ((t (:foreground ,yellow))))
       (font-lock-variable-name-face ((t (:foreground ,blue :bold t))))
       (font-lock-warning-face ((t (:foreground ,magenta :bold t))))
       (font-lock-doc-face ((t (:foreground ,cyan :italic t))))
       (font-lock-color-constant-face ((t (:foreground ,green))))
       (font-lock-comment-delimiter-face
        ((t (:foreground ,base1 :bold t))))
       (font-lock-doc-string-face ((t (:foreground ,green))))
       (font-lock-preprocessor-face ((t (:foreground ,orange))))
       (font-lock-reference-face ((t (:foreground ,cyan))))
       (font-lock-negation-char-face ((t (:foreground ,red))))
       (font-lock-other-type-face ((t (:foreground ,blue :italic t))))
       (font-lock-regexp-grouping-construct ((t (:foreground ,orange))))
       (font-lock-special-keyword-face ((t (:foreground ,magenta))))
       (font-lock-exit-face ((t (:foreground ,red))))
       (font-lock-other-emphasized-face
        ((t (:foreground ,violet :bold t :italic t))))
       (font-lock-regexp-grouping-backslash ((t (:foreground ,yellow))))

       (region ((t (:background ,base2))))
       (highlight ((t (:background ,base2))))
       (hl-line ((t (:background ,base2))))
       (isearch ((t (:foreground ,yellow :inverse-video t))))
       (highlight-80+
        ((t (:background ,magenta :foreground ,base2))))

       (minibuffer-prompt ((t (:foreground ,blue))))
       (link ((t (:foreground ,violet :underline t))))
       (link-visited ((t (:foreground ,magenta :underline t))))
       (comint-highlight-prompt ((t (:foreground ,blue))))
       (geiser-font-lock-doc-link ((t (:foreground ,violet :underline t))))

       (info-menu-star ((t (:foreground ,magenta))))
       (escape-glyph-face ((t (:foreground ,red))))
       (ido-subdir ((t (:foreground ,blue))))
       (ido-first-match ((t (:foreground ,green :bold t))))
       (ido-only-match ((t (:foreground ,green))))
       (undo-tree-visualizer-current-face ((t (:foreground ,red))))

       (flyspell-duplicate
        ((t (:background ,orange :background nil :bold t :underline t))))
       (flyspell-incorrect
        ((t (:foreground ,green :background nil :bold t :underline t))))

       (diff-added ((t (:foreground ,green :inverse-video t))))
       (diff-indicator-added ((t (:foreground ,green :inverse-video t))))
       (diff-changed ((t (:foreground ,yellow :inverse-video t))))
       (diff-indicator-changed ((t (:foreground ,yellow :inverse-video t))))
       (diff-removed ((t (:foreground ,red :inverse-video t))))
       (diff-indicator-removed ((t (:foreground ,red :inverse-video t))))
       (diff-header ((t (:background ,base1))))
       (diff-file-header
        ((t (:background ,base01 :foreground ,base1 :bold t))))
       (diff-refine-change ((t (:background ,base01))))

       (diredp-dir-heading
        ((t (:background nil :underline t :foreground ,magenta))))
       (diredp-inode+size ((t (:foreground ,blue :italic t))))
       (diredp-file-name ((t (:foreground ,base02))))
       (diredp-file-suffix ((t (:foreground ,base00))))
       (diredp-dir-priv
        ((t (:background nil :italic t :foreground ,base01))))
       (diredp-link-priv ((t (:foreground ,base1))))
       (diredp-rare-priv ((t (:foreground ,yellow :background nil))))
       (diredp-other-priv ((t (:foreground ,cyan :background nil))))
       (diredp-read-priv ((t (:background nil :foreground ,blue))))
       (diredp-write-priv ((t (:background nil :foreground ,violet))))
       (diredp-exec-priv ((t (:background nil :foreground ,magenta))))
       (diredp-no-priv ((t (:background nil :foreground ,base2))))
       (diredp-date-time ((t (:foreground ,blue))))
       (diredp-flag-mark ((t (:background nil :foreground ,base02))))
       (diredp-flag-mark-line ((t (:background ,base01 :foreground ,base2))))
       (diredp-deletion ((t (:background nil :foreground ,red))))
       (diredp-deletion-file-name ((t (:background nil :foreground ,red))))
       (diredp-ignored-file-name ((t (:foreground ,base00))))
       (diredp-compressed-file-suffix ((t (:foreground ,yellow))))
       (diredp-executable-tag ((t (:foreground ,magenta))))
       (diredp-symlink ((t (:foreground ,cyan))))

       (magit-section-title ((t (:foreground ,blue))))
       (magit-branch ((t (:foreground ,magenta))))
       (magit-item-highlight ((t (:background ,base2))))
       (magit-log-sha1 ((t (:foreground ,magenta))))

       (erc-default-face ((t (:foreground ,base03))))
       (erc-notice-face ((t (:foreground ,base1))))
       (erc-timestamp-face ((t (:foreground ,magenta))))
       (erc-direct-msg-face ((t (:foreground ,magenta))))
       (erc-nick-msg-face ((t (:foreground ,magenta :bold t))))
       (erc-pal-face ((t (:foreground ,blue))))
       (erc-input-face ((t (:foreground ,cyan :italic t))))
       (erc-current-nick-face ((t (:foreground ,magenta))))
       (erc-nick-default-face ((t (:foreground ,violet))))
       (erc-my-nick-face ((t (:foreground ,violet :italic t))))
       (erc-prompt-face ((t (:background nil :foreground ,blue))))

       (font-latex-warning-face ((t (:foreground ,magenta))))
       (font-latex-italic-face
        ((t (:foreground ,violet :italic t :underline nil))))
       (font-latex-bold-face ((t (:foreground ,base03 :bold t))))
       (font-latex-sectioning-1-face ((t (:foreground ,base03))))
       (font-latex-sectioning-2-face ((t (:foreground ,base02))))
       (font-latex-sectioning-3-face ((t (:foreground ,base01))))
       (font-latex-sectioning-4-face ((t (:foreground ,base1))))
       (font-latex-sectioning-5-face ((t (:foreground ,base01))))
       (font-latex-sedate-face ((t (:foreground ,blue))))

       (markdown-inline-code-face ((t (:foreground ,blue))))
       (markdown-pre-face ((t (:foreground ,blue))))

       (nxml-processing-instruction-delimiter-face ((t (:foreground ,base1))))
       (nxml-tag-delimiter-face ((t (:foreground ,base1))))
       (nxml-element-local-name-face ((t (:foreground ,base1))))
       (nxml-attribute-local-name-face ((t (:foreground ,blue))))
       (nxml-processing-instruction-target-face ((t (:foreground ,base1))))
       (nxml-attribute-value-face ((t (:foreground ,violet))))
       (nxml-attribute-value-delimiter-face ((t (:foreground ,violet))))
       (nxml-entity-ref-name-face ((t (:foreground ,yellow))))
       (nxml-entity-ref-delimiter-face ((t (:foreground ,yellow))))


       (w3m-anchor ((t (:foreground ,violet))))
       (w3m-current-anchor ((t (:foreground ,magenta))))
       (w3m-header-line-location-title ((t (:foreground ,base01))))
       (w3m-header-line-location-content ((t (:foreground ,base02))))
       (w3m-image-anchor ((t (:foreground ,violet))))

       (show-paren-match-face ((t (:background ,magenta :foreground ,base3))))
       (paren-face-match ((t (:background ,blue :foreground ,base3))))

       (clojure-parens ((t (:foreground ,base1))))
       (clojure-braces ((t (:foreground ,violet))))
       (clojure-brackets ((t (:foreground ,blue))))
       (clojure-java-call ((t (:foreground ,violet))))
       (clojure-keyword ((t (:foreground ,yellow))))
       (clojure-double-quote ((t (:foreground ,cyan))))
       (clojure-special ((t (:foreground ,magenta))))))))


;; Tomorrow Theme
;;
;; Originally by Chris Kempson https://github.com/ChrisKempson/Tomorrow-Theme
;; Ported to GNU Emacs by Chris Charles
(defun color-theme-tomorrow-real (background current-line
selection foreground comment red orange yellow green aqua blue
purple)
  "GNU Emacs port of Chris Kempson's Tomorrow theme. Port by Chris Charles."

    (color-theme-install
     `(color-theme-tomorrow-real
       ((background . ,background)
        (background-mode . dark)
        (border-color . "black")
        (cursor-color . "black")
        (foreground-color . ,foreground))

       ;; Built-in stuff (Emacs 23)
       (default ((t (:background ,background :foreground ,foreground))))
       (fringe ((t (:background ,current-line))))
       (minibuffer-prompt ((t (:foreground ,blue))))
       (mode-line ((t (:background ,current-line :foreground ,foreground))))
       (region ((t (:background ,selection))))

       ;; Font-lock stuff
       (font-lock-comment-face ((t (:foreground ,comment))))
       (font-lock-constant-face ((t (:foreground ,green))))
       (font-lock-doc-string-face ((t (:foreground ,comment))))
       (font-lock-function-name-face ((t (:foreground ,blue))))
       (font-lock-keyword-face ((t (:foreground ,purple))))
       (font-lock-string-face ((t (:foreground ,green))))
       (font-lock-type-face ((t (:foreground ,yellow))))
       (font-lock-variable-name-face ((t (:foreground ,red))))
       (font-lock-warning-face ((t (:foreground ,red))))

       ;; hl-line-mode
       (hl-line ((t (:background ,current-line))))

       ;; linum-mode
       (linum ((t (:background ,current-line :foreground ,foreground))))

       ;; org-mode
       (org-date ((t (:foreground ,purple))))
       (org-done ((t (:foreground ,green))))
       (org-hide ((t (:foreground ,current-line))))
       (org-link ((t (:foreground ,blue))))
       (org-todo ((t (:foreground ,red))))

       ;; show-paren-mode
       (show-paren-match-face ((t (:background ,blue :foreground ,current-line))))
       (show-paren-mismatch-face ((t (:background ,orange :foreground ,current-line)))))))

(defun color-theme-tomorrow ()
  "Base light Tomorrow theme."
  (interactive)
  (color-theme-tomorrow-real "#ffffff" "#e9efff" "#c5cce9" "#4d4d4c" "#8e908c"
                             "#c82829" "#f5871f" "#eab700" "#718c00" "#3e999f"
                             "#4271ae" "#8959a8"))

(defun color-theme-tomorrow-night ()
  "Dark Tomorrow theme."
  (interactive)
  (color-theme-tomorrow-real "#1d1f21" "#282a2e" "#373b41" "#c5c8c6" "#969896"
                             "#cc6666" "#de935f" "#f0c674" "#b5bd68" "#8abeb7"
                             "#81a2be" "#b294bb"))

(defun color-theme-tomorrow-night-eighties ()
  "Somewhat lighter dark Tomorrow theme."
  (interactive)
  (color-theme-tomorrow-real "#2d2d2d" "#393939" "#515151" "#cccccc" "#999999"
                             "#f2777a" "#f99157" "#ffcc66" "#99cc99" "#009999"
                             "#99cccc" "#cc99cc"))


(defun color-theme-tomorrow-night-blue ()
  "Dark Tomorrow theme with a blue background."
  (interactive)
  (color-theme-tomorrow-real "#002451" "#00346e" "#003f8e" "#ffffff" "#7285b7"
                             "#ff9da4" "#ffc58f" "#ffeead" "#d1f1a9" "#99ffff"
                             "#bbdaff" "#ebbbff"))


(provide 'custom-themes)
